#
# snowpatch - continuous integration for patch-based workflows
#
# Copyright (C) 2016 IBM Corporation
# Authors:
#     Russell Currey <ruscur@russell.cc>
#     Andrew Donnellan <andrew.donnellan@au1.ibm.com>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Cargo.toml - cargo build configuration file
#

[package]
name = "snowpatch"
version = "0.1.0"
authors = ["Russell Currey <ruscur@russell.cc>",
	   "Andrew Donnellan <andrew.donnellan@au1.ibm.com>"]
homepage = "https://github.com/ruscur/snowpatch"
repository = "https://github.com/ruscur/snowpatch.git"
documentation = "https://github.com/ruscur/snowpatch/tree/master/docs"
description = "continuous integration for patch-based workflows"
readme = "README.md"
license = "GPL-2.0+"
keywords = ["CI", "continuous integration", "patch", "patchwork", "jenkins",
	    "git"]

[[bin]]
name = "snowpatch"

[features]
default = []

[dependencies]
hyper = ">0.9.2" # 0.9.2 or later required for proxy support
git2 = "0.4"
rustc-serialize = "0.3"
url = "1.2"
mime = "0.2"
toml = "0.2"
tempdir = "0.3"
docopt = "0.6"
log = "0.3"
env_logger = "0.3"
clippy = {version = "*", optional = true}

[dev-dependencies]
yup-hyper-mock = "1.3"
